service: eie-microservices
# Check out our docs for more details
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  timeout: 10

plugins:
  - serverless-offline
#    - include-me-dir/**

# user service
functions:
  listUser:
    handler: routes/userRouter.getUser
    events:
      - httpApi:
          path: /user
          method: get

  createUser:
    handler: routes/userRouter.addUser
    events:
      - httpApi:
          path: /new-user
          method: post

  updateUser:
    handler: routes/userRouter.updateUser
    events:
      - httpApi:
          path: /user/{id}
          method: put

  deleteUser:
    handler: routes/userRouter.deleteUser
    events:
      - httpApi:
          path: /user/{id}
          method: delete
